import { ConsoleMenuItemStyle, ConsoleMenuIconStyle, ConsoleMenuIcon, ConsoleSubMenuItem, ConsoleMenuItem, ConsoleMenu } from 'domain/onsitexdomain';

let subPayroll:ConsoleSubMenuItem[], subInvoices:ConsoleSubMenuItem[], subReports:ConsoleSubMenuItem[], subAnalytics:ConsoleSubMenuItem[], subMessages:ConsoleSubMenuItem[], subConfig:ConsoleSubMenuItem[], subBeta:ConsoleSubMenuItem[];

[subPayroll, subInvoices, subReports, subAnalytics, subMessages, subConfig, subBeta] = [
  [ { parent: 'payroll' , title: 'Payroll'              , page: 'Payroll'               , tooltip: "Payroll"                              , icon: { class: "icomoon-payroll"                }, class: "panel-item child", hover: false, active: false, },
    { parent: 'payroll' , title: 'DPS'                  , page: 'DPS'                   , tooltip: "Daily Profit Sheets"                  , icon: { class: "icomoon-dps"                    }, class: "panel-item child", hover: false, active: false, },
],[ { parent: 'invoices', title: 'Tech Shift Reports'   , page: 'Tech Shift Reports'    , tooltip: "Technician Shift Reports"             , icon: { class: "icomoon-shift-reports"          }, class: "panel-item child", hover: false, active: false, },
    { parent: 'invoices', title: 'Pre-Authorization'    , page: 'Preauth HB'            , tooltip: "Halliburton Pre-Authorization"        , icon: { class: "icomoon-folder-verified-outline"}, class: "panel-item child", hover: false, active: false, },
    { parent: 'invoices', title: 'Halliburton'          , page: 'Invoicing HB Beta'     , tooltip: "Halliburton Invoicing"                , icon: { class: "icomoon-invoice"                }, class: "panel-item child", hover: false, active: false, },
    { parent: 'invoices', title: 'Logistics'            , page: 'Invoicing Logistics'   , tooltip: "Logistics Invoicing"                  , icon: { class: "fa fa-truck fa-flip-horizontal" }, class: "panel-item child", hover: false, active: false, },
    { parent: 'invoices', title: 'Keane'                , page: 'Invoicing Keane'       , tooltip: "Keane Invoicing"                      , icon: { class: "icomoon-invoice"                }, class: "panel-item child", hover: false, active: false, },
    { parent: 'invoices', title: 'Basic Energy'         , page: 'Invoicing Basic Energy', tooltip: "Basic Energy Invoicing"               , icon: { class: "icomoon-invoice"                }, class: "panel-item child", hover: false, active: false, },
],[ { parent: 'reports' , title: 'Work Reports'         , page: 'Work Reports'          , tooltip: "Work Reports"                         , icon: { class: "icomoon-reports-work"           }, class: "panel-item child", hover: false, active: false, },
    { parent: 'reports' , title: 'Other Reports'        , page: 'Other Reports'         , tooltip: "Other Reports (Travel/Training/etc.)" , icon: { class: "icomoon-reports-misc-large"     }, class: "panel-item child", hover: false, active: false, },
],[ { parent: 'issues'  , title: 'Flagged Work Reports' , page: 'Flagged Reports'       , tooltip: "Work Reports with problems"           , icon: { class: "icomoon-reports-flagged"        }, class: "panel-item child", hover: false, active: false, },
    { parent: 'issues'  , title: 'Flagged Misc Reports' , page: 'Flagged Other Reports' , tooltip: "Misc Reports with problems"           , icon: { class: "icomoon-reports-flagged"        }, class: "panel-item child", hover: false, active: false, },
    { parent: 'issues'  , title: 'Flagged Employees'    , page: 'Flagged Employees'     , tooltip: "Employee Records with problems"       , icon: { class: "icomoon-employee-problem"       }, class: "panel-item child", hover: false, active: false, },
    { parent: 'issues'  , title: 'Flagged Sites'        , page: 'Flagged Sites'         , tooltip: "Work Sites with problems"             , icon: { class: "icomoon-oil-derrick-problem"    }, class: "panel-item child", hover: false, active: false, },
],[ { parent: 'messages', title: 'Messages'             , page: 'Messages Beta'         , tooltip: "Messages to techs"                    , icon: { class: "icomoon-chatbubbles-outline"    }, class: "panel-item child", hover: false, active: false, },
// ],[ { parent: 'messages', title: 'Messages'             , page: 'Messages'              , tooltip: "Messages to techs"                    , icon: { class: "icomoon-chatbubbles-outline"    }, class: "panel-item child", hover: false, active: false, },
    { parent: 'messages', title: 'Comments'             , page: 'Comments'              , tooltip: "Comments from techs"                  , icon: { class: "icomoon-chatboxes-outline"      }, class: "panel-item child", hover: false, active: false, },
],[ { parent: 'config'  , title: 'Options'              , page: 'Options'               , tooltip: "OnSiteX Console Global Options"       , icon: { class: "icomoon-settings-outline"       }, class: "panel-item child", hover: false, active: false, },
    { parent: 'config'  , title: 'Advanced Options'     , page: 'Options'               , tooltip: "OnSiteX Console Advanced Options"     , icon: { class: "icomoon-options-outline"        }, class: "panel-item child", hover: false, active: false, },
    { parent: 'config'  , title: 'Configuration'        , page: 'Config Values'         , tooltip: "OnSiteX Configuration"                , icon: { class: "icomoon-keypad-outline"         }, class: "panel-item child", hover: false, active: false, },
    { parent: 'config'  , title: 'Save Preferences'     , page: 'Config Values'         , tooltip: "Save Preferences to local storage"    , icon: { class: "icomoon-box-check-yes"          }, class: "panel-item child", hover: false, active: false, },
    { parent: 'config'  , title: 'Reauthenticate'       , page: 'Config Values'         , tooltip: "Log in to server again"               , icon: { class: "icomoon-log-in"                 }, class: "panel-item child", hover: false, active: false, },
    { parent: 'config'  , title: 'Restart App'          , page: 'Config Values'         , tooltip: "Restart Console application"          , icon: { class: "icomoon-reset"                  }, class: "panel-item child", hover: false, active: false, },
    { parent: 'config'  , title: 'Logout'               , page: 'Logout'                , tooltip: "Logout of app"                        , icon: { class: "icomoon-log-out"                }, class: "panel-item child", hover: false, active: false, },
],[
  { parent: 'dev'     , title: 'Reports Gamma'        , page: 'Reports Gamma'         , tooltip: "Work Reports (ngx-datagrid version)"  , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Reports Logistics'    , page: 'Reports Logistics'     , tooltip: "Logistics Reports"                    , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Invoicing HB (old)'   , page: 'Invoicing HB'          , tooltip: "Halliburton Invoicing (old)"          , icon: { class: "icomoon-invoice special"        }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Employees (old)'      , page: 'Employees Beta'        , tooltip: "Employees Beta (monaco version)"      , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Reports Alpha'        , page: 'Reports Alpha'         , tooltip: "Work Reports (datagrid version)"      , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Payroll Alpha'        , page: 'Payroll Alpha'         , tooltip: "Payroll (datagrid version)"           , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Schedule Choose Beta' , page: 'Scheduling Beta Choose', tooltip: "Scheduling (beta version)"            , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Scheduling Beta'      , page: 'Scheduling Beta'       , tooltip: "Scheduling (beta version)"            , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Test Notifications'   , page: 'NotifyTest'            , tooltip: "Test notification system"             , icon: { class: "icomoon-notification2 special"  }, class: "panel-item child", hover: false, active: false, },
  { parent: 'dev'     , title: 'Testing'              , page: 'testing'               , tooltip: "Test screen (for developers)"         , icon: { class: "icomoon-experiment special"     }, class: "panel-item child", hover: false, active: false, }, ],
];
export const menuItems:ConsoleMenu = {
  home      : { title: 'Console Home'  , page: 'OnSiteX Console'     , role: "usr", tooltip: "Console Home Page"                  , icon: { class: "icomoon-home-outline"         , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  // schedule  : { title: 'Schedule'      , page: 'Schedule Choose'     , role: "usr", tooltip: "Scheduling"                         , icon: { class: "icomoon-schedule"             , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  schedule  : { title: 'Schedule'      , page: 'Scheduling'     , role: "usr", tooltip: "Scheduling"                         , icon: { class: "icomoon-schedule"             , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  // employees : { title: 'Employees'     , page: 'Employees Beta'      , role: "usr", tooltip: "Employee list"                      , icon: { class: "icomoon-people-outline"       , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  employees : { title: 'Employees'     , page: 'Employees'           , role: "usr", tooltip: "Employee list"                      , icon: { class: "icomoon-people-outline"       , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  sites     : { title: 'Work Sites'    , page: 'Work Sites'          , role: "usr", tooltip: "Work Site list"                     , icon: { class: "icomoon-oil-well"             , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  payroll   : { title: 'Payroll'       , page: 'Payroll'             , role: "usr", tooltip: "Payroll reports"                    , icon: { class: "icomoon-payroll"              , style: {color: 'black'} }, class: "panel-item parent", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: true  , submenu: subPayroll  , },
  invoices  : { title: 'Invoices'      , page: 'Invoice'             , role: "usr", tooltip: "Invoicing"                          , icon: { class: "icomoon-invoice"              , style: {color: 'black'} }, class: "panel-item parent", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: true  , submenu: subInvoices , },
  reports   : { title: 'Reports'       , page: 'Reports Gamma'       , role: "usr", tooltip: "Reports submitted by techs"         , icon: { class: "icomoon-reports"              , style: {color: 'black'} }, class: "panel-item parent", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  issues    : { title: 'Issues'        , page: 'Issues'              , role: "usr", tooltip: "Problems, flagged reports, etc."    , icon: { class: "icomoon-flag-checkered"       , style: {color: 'black'} }, class: "panel-item parent", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: true  , submenu: subAnalytics, },
  messages  : { title: 'Messages'      , page: 'Messages'            , role: "usr", tooltip: "Messages to/from techs"             , icon: { class: "icomoon-chatbubbles-outline"  , style: {color: 'black'} }, class: "panel-item parent", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: true  , submenu: subMessages , },
  phones    : { title: 'Phones'        , page: 'Tech Phones'         , role: "usr", tooltip: "Tech phones and login history"      , icon: { class: "icomoon-phone-portrait"       , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  geo       : { title: 'Geolocation'   , page: 'Geolocation'         , role: "usr", tooltip: "Tech locations"                     , icon: { class: "icomoon-location-history-map" , style: {color: 'black'} }, class: "panel-item single", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: false , submenu: []          , },
  config    : { title: 'Configuration' , page: 'Config Values'       , role: "usr", tooltip: "OnSiteX configuration data"         , icon: { class: "icomoon-settings-outline"     , style: {color: 'black'} }, class: "panel-item parent", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: true  , submenu: subConfig   , },
  dev       : { title: 'Developer'     , page: 'Developer'           , role: "dev", tooltip: "Developer Testing"                  , icon: { class: "icomoon-experiment special"   , style: {color: 'red'  } }, class: "panel-item parent", style: {'max-height': '1000px', }, hover: false, active: false, showSubMenu: false , hasSubmenu: true  , submenu: subBeta     , },
};

export const menuArray:ConsoleMenuItem[] = [];

export { ConsoleMenuItemStyle, ConsoleMenuIconStyle, ConsoleMenuIcon, ConsoleSubMenuItem, ConsoleMenuItem, ConsoleMenu  };
